# This is a basic workflow to help you get started with Actions

name: deploy storage

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
    - '.github/workflows/**'
  
  workflow_dispatch:
  
env:
  AZ_RG_Name: 'RG20'
  AZ_RG_Location: 'WestEurope'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login to Azure
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{secrets.AZ_CLIENT_ID}}
          tenant-id: ${{secrets.AZ_TENANT_ID}}
          subscription-id: ${{secrets.AZ_SUB_ID}}
      - name: create RG
        uses: Azure/cli@v2.1.0
        with:
          inlineScript:
            az group create --name ${{env.AZ_RG_Name}} --location ${{env.AZ_RG_Location}}

      - name: deploy storage Bicep
        uses: Azure/arm-deploy@v2  
        id: deploy-sa
        with:
          resourceGroupName:  ${{env.AZ_RG_Name}}
          template: ./storage.bicep
          deploymentName: ${{github.run_number}}
